// MAIN CONST ACTION TYPE
export const ADD_TO_CART = "ADD_TO_CART";

// VIEW DETAIL
export const VIEW_DETAIL = "VIEW_DETAIL";
export const CLOSE_DETAIL = "CLOSE_DETAIL";

// CART CONST ACTION TYPE

export const VIEW_CART = "VIEW_CART";
export const CLOSE_CART = "CLOSE_CART";
export const SHOW_MINI_CART = "SHOW_MINI_CART";
export const HIDE_MINI_CART = "HIDE_MINI_CART";

// CART ITEM CONST ACTION TYPE
export const DELETE_FROM_CART = "DEL_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const INCREASE_ITEM_CART = "INCREASE_ITEM_CART";
export const DECREASE_ITEM_CART = "DECREASE_ITEM_CART";
